[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[env]
DEFMT_LOG="info"
ESP_HAL_CONFIG_PLACE_RMT_DRIVER_IN_RAM="true"

[build]
rustflags = [
    # Required by esp-backtrace, but may negatively impact code performance
    "-C", "force-frame-pointers",
    # Required by esp-hal
    "-C", "link-arg=-Tlinkall.x",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
